spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate # Don't modify schema in production!
    show-sql: false

logging:
  level:
    com.skycommerce: INFO
